# Generated by Django 5.1 on 2025-08-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.TextField(blank=True, help_text='Store image URL, path, or Base64 text', null=True),
        ),
    ]
