# Generated by Django 5.1 on 2024-12-25 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='customer',
        ),
    ]
