# Generated by Django 5.1 on 2025-01-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('pending', 'Pending'), ('warehoused', 'Warehoused'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upi', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('warehoused', 'Warehoused'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderpaymentstatuschange',
            name='status_from',
            field=models.CharField(choices=[('pending', 'Pending'), ('warehoused', 'Warehoused'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=255),
        ),
        migrations.AlterField(
            model_name='orderpaymentstatuschange',
            name='status_to',
            field=models.CharField(choices=[('pending', 'Pending'), ('warehoused', 'Warehoused'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=255),
        ),
    ]
