# Generated by Django 5.1 on 2025-01-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='upi', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('ready_for_delivery', 'Ready for Delivery'), ('goods_collected', 'Goods Collected'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderpaymentstatuschange',
            name='status_from',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], max_length=255),
        ),
        migrations.AlterField(
            model_name='orderpaymentstatuschange',
            name='status_to',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], max_length=255),
        ),
        migrations.AlterField(
            model_name='orderstatuschange',
            name='status_from',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('ready_for_delivery', 'Ready for Delivery'), ('goods_collected', 'Goods Collected'), ('delivered', 'Delivered')], max_length=255),
        ),
        migrations.AlterField(
            model_name='orderstatuschange',
            name='status_to',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('ready_for_delivery', 'Ready for Delivery'), ('goods_collected', 'Goods Collected'), ('delivered', 'Delivered')], max_length=255),
        ),
    ]
