# Generated by Django 5.1 on 2025-01-23 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_payment_method_and_more'),
        ('staff', '0003_remove_staff_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='staff.staff'),
        ),
        migrations.CreateModel(
            name='OrderAssignedToChange',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('assigned_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_from_changes', to='staff.staff')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_to_changes', to='staff.staff')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to_changes', to='orders.order')),
            ],
        ),
    ]
