# Generated by Django 5.1 on 2025-01-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_assigned_to_orderassignedtochange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderassignedtochange',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
