# Generated by Django 5.1 on 2025-01-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_created_on_orderassignedtochange_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_image',
            field=models.TextField(blank=True),
        ),
    ]
