# Generated by Django 5.1 on 2024-11-15 11:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('subcategories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('org_id', models.PositiveIntegerField(blank=True, null=True)),
                ('mfg', models.DateField(default=django.utils.timezone.now)),
                ('product_life', models.PositiveIntegerField(default=1)),
                ('product_image1', models.TextField(blank=True, null=True)),
                ('product_image2', models.TextField(blank=True, null=True)),
                ('availability', models.BooleanField(default=True)),
                ('product_type', models.CharField(choices=[('veg', 'Vegetarian'), ('nonveg', 'Non-Vegetarian'), ('organic', 'Organic'), ('non-organic', 'Non-Organic')], default='organic', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='categories.category')),
                ('subcategory', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='subcategories.subcategory')),
            ],
        ),
    ]
