# Generated by Django 5.1 on 2024-12-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_products_category_alter_products_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='subcategory_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
