# Generated by Django 5.1 on 2024-12-30 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_alter_category_options'),
        ('inventory', '0001_initial'),
        ('product', '0004_products_category_name_products_subcategory_name'),
        ('subcategories', '0002_subcategory_category_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
