# Generated by Django 5.1 on 2024-11-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('billing_address', models.TextField()),
                ('shipping_address', models.TextField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.CharField(default='Pending', max_length=20)),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_paid_by', models.CharField(default='Credit Card', max_length=20)),
            ],
        ),
    ]
