# Generated by Django 5.1 on 2024-12-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_org_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_date',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_paid_by',
            new_name='payment_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
