# Generated by Django 5.1 on 2024-12-31 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_city_order_country_order_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='id',
        ),
    ]
