# Generated by Django 5.1 on 2024-11-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='org_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
