# Generated by Django 5.1 on 2025-01-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile_number',
            field=models.CharField(default='0992123123', max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
