# Generated by Django 5.1 on 2024-12-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customers_org_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
