# Generated by Django 5.1 on 2025-01-26 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_city_alter_customer_first_name_and_more'),
        ('customers', '0005_alter_customer_city_alter_customer_first_name_and_more'),
    ]

    operations = [
    ]
