# Generated by Django 5.1 on 2024-11-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
