# Generated by Django 5.1 on 2024-11-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='org_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
