# Generated by Django 5.1 on 2025-01-23 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staff_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='city',
        ),
    ]
