# Generated by Django 5.1 on 2025-01-13 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Store Name')),
                ('address1', models.TextField(verbose_name='Address Line 1')),
                ('address2', models.TextField(blank=True, null=True, verbose_name='Address Line 2')),
                ('address3', models.TextField(blank=True, null=True, verbose_name='Address Line 3')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stores', to='organisations.organisation')),
            ],
        ),
    ]
