# Generated by Django 5.1 on 2024-11-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='org_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
