# Generated by Django 5.1 on 2024-12-30 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_order_amount_order_amount_and_more'),
        ('order_items', '0003_alter_orderitems_id'),
        ('product', '0004_products_category_name_products_subcategory_name'),
        ('product', '0005_rename_products_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('org_id', models.PositiveIntegerField(blank=True, null=True)),
                ('product_name', models.CharField(max_length=255)),
                ('product_qty', models.PositiveIntegerField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_discounted', models.BooleanField(default=False)),
                ('product_subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.product')),
            ],
        ),
        migrations.DeleteModel(
            name='OrderItems',
        ),
    ]
