# Generated by Django 5.1 on 2025-01-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_items', '0004_orderitem_delete_orderitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_image',
            field=models.TextField(default='/assets/img/logo/pamosa_logo.png'),
            preserve_default=False,
        ),
    ]
