# Generated by Django 5.1 on 2024-12-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcategories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='category_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
