# Generated by Django 5.1 on 2024-12-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Store Name"
                    ),
                ),
                ("address1", models.TextField(verbose_name="Address Line 1")),
                (
                    "address2",
                    models.TextField(
                        blank=True, null=True, verbose_name="Address Line 2"
                    ),
                ),
                (
                    "address3",
                    models.TextField(
                        blank=True, null=True, verbose_name="Address Line 3"
                    ),
                ),
            ],
        ),
    ]
