name: Deploy to Ubuntu Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to Ubuntu Server
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: pamosapicks.com
          USER_NAME: ubuntu
      
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -i private_key -o StrictHostKeyChecking=no ${USER_NAME}@${HOSTNAME} << 'EOF'
            # Navigate to repository directory
            cd /home/ubuntu/repos/ecommerce
            
            # Pull latest changes from main branch
            git fetch origin
            git checkout main
            git pull origin main
            
            # Show latest commit for verification
            echo "Latest commit:"
            git log -1 --oneline
            
            # Copy updated code to project directory
            echo "Updating project files..."
            rsync -av --exclude='.git/' --exclude='venv/' --exclude='logs/' --exclude='__pycache__/' --exclude='*.pyc' /home/ubuntu/repos/ecommerce/ /home/ubuntu/ecommerce/
            
            # Activate virtual environment and install/update dependencies
            cd /home/ubuntu/ecommerce
            source venv/bin/activate
            pip install -r /home/ubuntu/repos/ecommerce/requirements.txt
            
            # Run database migrations
            cd restserver
            python manage.py migrate --settings=restserver.settings.production
            
            # Collect static files
            python manage.py collectstatic --noinput --settings=restserver.settings.production
            
            # Restart services
            echo "Restarting services..."
            pm2 restart all
            
            echo "Deployment completed successfully!"
          EOF